### ISSUE TITLE
	Group Member Registration

### ISSUE THREAD

**Issue by sachsk** [avniproject/Swadhar#4]

**Comment by nupoorkhandelwal** [comment]
What is the purpose of this Group member registration? Don't see anything relevant to it in the requirements sheet.

**Comment by kuldeeplodha** [comment]
We created this when we were working to create a group subject type then Arjun suggested we use the same member type as the family member for the ECCDE attend form. So Now we don't need this. We can delete this.

**Comment by nupoorkhandelwal** [comment]
Mark the issue as Closed then.
